config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  resources :staticpages, only: :index
  root "staticpages#index"
  namespace :admin do
    root "admin/users#index"
    resources :users, :categories, :products, :suggests
  end
  resources :products, only: [:index, :show] do
    resources :comments
  end
  resources :categories, only: [:index, :show]
  resources :suggests
  resources :carts
  resources :orders
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

  def index
    @products_newest = Product.newest.limit_product
  end
end

app/views/staticpages/index.html.erb
<div class="rows aqc">
  <div class="banner">
    <%= image_tag "banner.jpg" %>
  </div>
  <h1><%= t "newest" %></h1>
  <div class="content_grid">
    <% @products_newest.each do |product| %>
    <div class="col_1_of_3 span_1_of_3">
      <div class="view view-first">
        <div class="inner_content clearfix">
          <div class="product_image">
            <%= link_to product_path(product) do %>
            <%= image_tag "" %>
            <% end %>
            <div class="mask">
              <div class="info"><%= t "product.quick_view" %></div>
            </div>
            <div class="product_container">
              <div class="cart-left">
                <p class="title"> <%= product.name %></p>
              </div>
              <div class="price"><%= number_to_currency product.price %></div>
              <span class="reducedfrom"><%= number_to_currency product.discount %></span>
              <%= link_to cart_path(product.id), remote: true, method: :patch, class: "btn btn-danger" do %>
            <span class="glyphicon glyphicon-shopping-cart"></span>
              <%= t "cart.add_cart" %>
              <% end %>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <%= link_to t("show_more"), products_path, class: "fa fa-arrow-circle-o-right" %>
  <div class="banner">
    <%= image_tag "banner2.jpg" %>
  </div>
</div>