config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  resources :staticpages, only: :index
  root "staticpages#index"
  namespace :admin do
    root "admin/users#index"
    resources :users, :categories, :products, :suggests
  end
  resources :products, only: [:index, :show] do
    resources :comments
  end
  resources :categories, only: [:index, :show]
  resources :suggests
  resources :carts
  resources :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @order = Order.new
  end

  def update
    @cart.add_item params[:id]
    session[:cart] = @cart.sort
    respond_to do |format|
      format.js {render :update}
    end
  end

  def edit
    item = @cart.find_item params[:id]
    if item.quantity > 1
      item.decrement
      session[:cart] = @cart.sort
    end
    respond_to do |format|
      format.js {render :update}
    end
  end

  def destroy
    cart = session[:cart]
    item = cart["items"].find{|item| item["product_id"] == params[:id]}
    if item
      cart["items"].delete item
      create_cart
    end
    respond_to do |format|
      format.js {render :update}
    end
  end
end

app/views/carts/_list_product.html.erb
<table class="table table-striped table-bordered table-hover table-condensed" id="cart">
  <thead>
    <th><%= t "cart.product_name" %></th>
    <th><%= t "cart.product_price" %></th>
    <th></th>
    <th><%= t "cart.product_quantity" %></th>
    <th><%= t "cart.total_price" %></th>
    <th></th>
  </thead>
  <tbody>
    <% @cart.items.each do |item| %>
    <td><%= link_to item.product.name, product_path(item.product.id) %></td>
    <td><%= number_to_currency item.product.price %></td>

    <td><input value="<%= item.quantity %>" class="input-text qty"  disabled/></td>

    <td><%= link_to cart_path(item.product), remote: true, method: :patch, class: "increase" do %>
            <%= button_tag t("cart.increase"), class: "increase" %>
          <% end %>
          <%= link_to edit_cart_path(item.product), remote: true, class: "decrease" do %>
            <%= button_tag t("cart.decrease"),class: "decrease"%>
          <% end %>
    </td>
    <td><%= item.total_price %></td>
    <td><%= link_to cart_path(item.product_id), method: :delete, remote: true, class: "icon-rm" do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
    </td>

  </tbody>
  <% end %>
</table>

app/views/carts/index.html.erb
<% if @cart.present? %>
  <b><p><%= t "cart.total_price"%></b>
  <span class="total-item"><%= @cart.total_price %></span>
  <%= render "list_product" %>
<button  class= "btn btn-lg btn-primary" id="show"><%= t "cart.checkout" %></button>
<br>
<%= t "cart.note_message" %>
<div class="form_checkout">
  <%= form_for @order do |f| %>
    <p><%= f.text_area :message, class: "form-control", placeholder: t("cart.placeholder_message") %></p>
    <p><%= f.submit t("cart.order"), class: "btn btn-lg btn-primary btn-block" %></p>
  <% end %>
</div>
<% end %>

app/views/carts/update.js.erb
$('.em-topcart-qty').text('<%= @cart.count %>');
$('.total-item').text('<%= @cart.total_price %>');
$('#cart').html('<%= j render "list_product" %>');