config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  resources :staticpages, only: :index
  root "staticpages#index"
  namespace :admin do
    root "admin/users#index"
    resources :users, :categories, :products, :suggests
  end
  resources :products, only: [:index, :show] do
    resources :comments
  end
  resources :categories, only: [:index, :show]
  resources :suggests
  resources :carts
  resources :orders
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  scope :asc_by_name, ->{order :name}
  scope :limit_category, ->{limit Settings.category.limit}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin_application"
  before_action :find_category, except: [:create, :new, :index]
  before_action :verify_admin

  def index
    @categories = Category.asc_by_name.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
    @products = @category.products.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to admin_categories_path
    else
      @errors_count = @category.errors.size
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      redirect_to admin_category_path
    else
      @errors_count = @category.errors.size
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "category.deleted"
      redirect_to admin_categories_path
    else
      flash[:warning] = t "category.destroy_fail"
      redirect_to root_path
    end
  end

  private
  def category_params
    params.require(:category).permit :name
  end

  def find_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:warning] = t "category.not_found"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: :show

  def index
    @categories = Category.asc_by_name
  end

  def show
    @products = @category.products.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:warning] = "not_found"
      redirect_to root_path
    end
  end
end

app/views/categories/_categories.html.erb
<% categories.each do |category| %>
  <li class="level0">
    <%= link_to category.name, category_path(category) %>
  </li>
<% end %>
<%= link_to t("category.show_more"), categories_path %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <li class="level0"><%= link_to category.name, category_path(category) %></li>
<% end %>

app/views/categories/show.html.erb
<div class="content_grid">
  <% @products.each do |product| %>
  <div class="col_1_of_3 span_1_of_3">
    <div class="view view-first">
      <div class="inner_content clearfix">
        <div class="product_image">
          <%= link_to product_path(product) do %>
            <%= image_tag product.image.url if product.image? %>
          <% end %>
          <div class="mask">
            <div class="info"><%= t "product.quick_view" %></div>
          </div>
          <div class="product_container">
            <div class="cart-left">
              <p class="title"> <%= product.name %></p>
            </div>
            <div class="price"><%= number_to_currency product.price %></div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= will_paginate @products %>