config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks#create"}
  resources :staticpages, only: :index
  root "staticpages#index"
  namespace :admin do
    root "admin/users#index"
    resources :users, :categories, :products, :suggests
  end
  resources :products, only: [:index, :show] do
    resources :comments
  end
  resources :categories, only: [:index, :show]
  resources :suggests
  resources :carts
  resources :orders
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user

  mount_uploader :image, PictureUploader

  validates :name, presence: :true
  validates :body, presence: :true, length: {minimum: 10}
  validates :price, numericality: { greater_than_or_equal_to: 0, allow_nil: true }

  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/suggests_controller.rb
class Admin::SuggestsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_suggest, only: [:show, :update, :edit, :destroy]
  before_action :verify_admin

  def index
    @suggests = Suggest.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
  end

  def edit
  end

  def update
    if @suggest.update_attributes suggest_params
      flash[:success] = t "suggest.update"
      redirect_to admin_suggests_path
    else
      flash[:warning] = t "suggest.update_fail"
      render :edit
    end
  end

  def destroy
    if @suggest.destroy
      flash[:success] = t "suggest.deleted"
      redirect_to suggests_path
    else
      flash[:warning] = t "suggest.delete_fail"
      redirect_to root_path
    end
  end

  private
  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    unless @suggest
      flash[:warning] = t "suggest.not_found"
      redirect_to root_path
    end
  end

  def suggest_params
    params.require(:suggest).permit :name, :body, :image, :price, :status
  end
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_suggest, except: [:new, :create, :index]

  def index
    @suggests = current_user.suggests.newest.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
  end

  def new
    @suggest = Suggest.new
  end

  def create
    @suggest = Suggest.new suggest_params
    if @suggest.save
      UserMailer.suggest_mail(@suggest).deliver_now
      flash[:success] = t "suggest.create_suggest"
      redirect_to @suggest
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @suggest.update_attributes suggest_params
      flash[:success] = t "suggest.update"
      redirect_to @suggest
    else
      flash[:warning] = t "suggest.update_fail"
      render :edit
    end
  end

  def destroy
    if @suggest.destroy
      flash[:success] = t "suggest.deleted"
      redirect_to suggests_path
    else
      flash[:warning] = t "suggest.delete_fail"
      redirect_to root_path
    end
  end

  private
  def load_suggest
    @suggest = Suggest.find_by id: params[:id]
    unless @suggest
      flash.now[:warning] = t "suggest.not_found"
      redirect_to root_path
    end
  end

  def suggest_params
    params.require(:suggest).permit :name, :body, :image, :price, :status, :user_id
  end
end

app/views/admin/suggests/edit.html.erb
<%= simple_form_for [:admin, @suggest], :html => {:multipart => true} do |f| %>
<%= render "shared/error_messages", object: @suggest %>
  <div id="form-main">
    <div id="form-div">
      <div class="form" id="form1">
        <%= f.input :name, disabled: true, label: t("suggest.name_label") %>

        <%= f.input :body, disabled: true, label: t("suggest.message") %>

        <%= f.input :price, disabled: true, label: t("suggest.price_suggest") %>

        <%= f.input :status, check_box: t("suggest.price_suggest") %>

        <%= f.input :image, disabled: true, as: :file, label: t("suggest.image") %>

        <%= f.button :submit,  class: "btn btn-lg btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/suggests/index.html.erb
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th><%= t "suggest.name_label" %></th>
      <th><%= t "suggest.message" %></th>
      <th><%= t "suggest.price_suggest" %></th>
      <th><%= t "suggest.status" %></th>
      <th><%= t "suggest.image" %></th>
    </tr>
  </thead>
  <% @suggests.each do |suggest| %>
  <tbody>
    <td><%= link_to suggest.name, admin_suggest_path(suggest) %></td>
    <td><%= suggest.body %></td>
    <td><%= number_to_currency suggest.price %></td>
    <td><%= suggest.status? ? t("suggest.sent") : t("suggest.pending") %></td>
    <td>
      <%= link_to admin_suggest_path(suggest) do %>
        <%= image_tag suggest.image.url %>
      <% end %>
    </td>
    <% unless suggest.status? %>
    <td><%= link_to t("suggest.edits"), edit_admin_suggest_path(suggest) %></td>
    <td><%= link_to t("suggest.delete"), admin_suggest_path(suggest), method: :delete, data: {confirm: "sure?"} %></td>
    <% end %>
  </tbody>
  <% end %>
</table>
<%= will_paginate @suggests %>

app/views/admin/suggests/show.html.erb
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th><%= t "suggest.name_label" %></th>
      <th><%= t "suggest.message" %></th>
      <th><%= t "suggest.price" %></th>
      <th><%= t "suggest.status" %></th>
      <th><%= t "suggest.image" %></th>
    </tr>
  </thead>
  <tbody>
      <td><%= @suggest.name %></td>
      <td><%= @suggest.body %></td>
      <td><%= number_to_currency @suggest.price %></td>
      <td><%= @suggest.status %></td>
      <td><%= image_tag @suggest.image.url if @suggest.image? %></td>
      <% if @suggest.status?  %>
        <td colspan="3">
          <%= link_to t("create"), new_admin_product_path( g_price: @suggest.price,
            g_name: @suggest.name, g_body: @suggest.body ) %>
        </td>
      <% end %>
  </tbody>
</table>